// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: protos/envelope.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyBtcDepositsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64           `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Txs    []*BtcDepositTx `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
}

func (x *VerifyBtcDepositsRequest) Reset() {
	*x = VerifyBtcDepositsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_envelope_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyBtcDepositsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBtcDepositsRequest) ProtoMessage() {}

func (x *VerifyBtcDepositsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBtcDepositsRequest.ProtoReflect.Descriptor instead.
func (*VerifyBtcDepositsRequest) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyBtcDepositsRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VerifyBtcDepositsRequest) GetTxs() []*BtcDepositTx {
	if x != nil {
		return x.Txs
	}
	return nil
}

type BtcDepositTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash   string `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Memo     string `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	Receiver string `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender   string `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount   string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *BtcDepositTx) Reset() {
	*x = BtcDepositTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_envelope_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcDepositTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcDepositTx) ProtoMessage() {}

func (x *BtcDepositTx) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcDepositTx.ProtoReflect.Descriptor instead.
func (*BtcDepositTx) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *BtcDepositTx) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *BtcDepositTx) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *BtcDepositTx) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *BtcDepositTx) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *BtcDepositTx) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type VerifyBtcDepositsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *VerifyBtcDepositsResponse) Reset() {
	*x = VerifyBtcDepositsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_envelope_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyBtcDepositsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBtcDepositsResponse) ProtoMessage() {}

func (x *VerifyBtcDepositsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBtcDepositsResponse.ProtoReflect.Descriptor instead.
func (*VerifyBtcDepositsResponse) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyBtcDepositsResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VerifyBtcDepositsResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerifyBtcDepositsResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type VerifyInscriptionDepositsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *VerifyInscriptionDepositsRequest) Reset() {
	*x = VerifyInscriptionDepositsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_envelope_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyInscriptionDepositsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInscriptionDepositsRequest) ProtoMessage() {}

func (x *VerifyInscriptionDepositsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInscriptionDepositsRequest.ProtoReflect.Descriptor instead.
func (*VerifyInscriptionDepositsRequest) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyInscriptionDepositsRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type InscriptionDepositTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash   string `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Memo     string `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	Receiver string `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender   string `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount   string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *InscriptionDepositTx) Reset() {
	*x = InscriptionDepositTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_envelope_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InscriptionDepositTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscriptionDepositTx) ProtoMessage() {}

func (x *InscriptionDepositTx) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscriptionDepositTx.ProtoReflect.Descriptor instead.
func (*InscriptionDepositTx) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *InscriptionDepositTx) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *InscriptionDepositTx) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *InscriptionDepositTx) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *InscriptionDepositTx) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *InscriptionDepositTx) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type VerifyInscriptionDepositsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *VerifyInscriptionDepositsResponse) Reset() {
	*x = VerifyInscriptionDepositsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_envelope_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyInscriptionDepositsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInscriptionDepositsResponse) ProtoMessage() {}

func (x *VerifyInscriptionDepositsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInscriptionDepositsResponse.ProtoReflect.Descriptor instead.
func (*VerifyInscriptionDepositsResponse) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyInscriptionDepositsResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VerifyInscriptionDepositsResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerifyInscriptionDepositsResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type VerifyBtcWithdrawalsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *VerifyBtcWithdrawalsRequest) Reset() {
	*x = VerifyBtcWithdrawalsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_envelope_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyBtcWithdrawalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBtcWithdrawalsRequest) ProtoMessage() {}

func (x *VerifyBtcWithdrawalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBtcWithdrawalsRequest.ProtoReflect.Descriptor instead.
func (*VerifyBtcWithdrawalsRequest) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyBtcWithdrawalsRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type VerifyBtcWithdrawalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *VerifyBtcWithdrawalsResponse) Reset() {
	*x = VerifyBtcWithdrawalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_envelope_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyBtcWithdrawalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBtcWithdrawalsResponse) ProtoMessage() {}

func (x *VerifyBtcWithdrawalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBtcWithdrawalsResponse.ProtoReflect.Descriptor instead.
func (*VerifyBtcWithdrawalsResponse) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyBtcWithdrawalsResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VerifyBtcWithdrawalsResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerifyBtcWithdrawalsResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type VerifyInscriptionWithdrawalsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *VerifyInscriptionWithdrawalsRequest) Reset() {
	*x = VerifyInscriptionWithdrawalsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_envelope_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyInscriptionWithdrawalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInscriptionWithdrawalsRequest) ProtoMessage() {}

func (x *VerifyInscriptionWithdrawalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInscriptionWithdrawalsRequest.ProtoReflect.Descriptor instead.
func (*VerifyInscriptionWithdrawalsRequest) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyInscriptionWithdrawalsRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type VerifyInscriptionWithdrawalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *VerifyInscriptionWithdrawalsResponse) Reset() {
	*x = VerifyInscriptionWithdrawalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_envelope_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyInscriptionWithdrawalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInscriptionWithdrawalsResponse) ProtoMessage() {}

func (x *VerifyInscriptionWithdrawalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_envelope_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInscriptionWithdrawalsResponse.ProtoReflect.Descriptor instead.
func (*VerifyInscriptionWithdrawalsResponse) Descriptor() ([]byte, []int) {
	return file_protos_envelope_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyInscriptionWithdrawalsResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VerifyInscriptionWithdrawalsResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerifyInscriptionWithdrawalsResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_protos_envelope_proto protoreflect.FileDescriptor

var file_protos_envelope_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x22, 0x5c, 0x0a, 0x18, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x42, 0x74, 0x63, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x28, 0x0a, 0x03, 0x74, 0x78, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x42, 0x74,
	0x63, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x54, 0x78, 0x52, 0x03, 0x74, 0x78, 0x73, 0x22,
	0x87, 0x01, 0x0a, 0x0c, 0x42, 0x74, 0x63, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x54, 0x78,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6d,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6b, 0x0a, 0x19, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x42, 0x74, 0x63, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3a, 0x0a, 0x20, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x22, 0x8f, 0x01, 0x0a, 0x14, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x54, 0x78, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x73, 0x0a, 0x21, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x1b, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x42, 0x74, 0x63, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x22, 0x6e, 0x0a, 0x1c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x42, 0x74, 0x63, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x3d, 0x0a, 0x23, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22,
	0x76, 0x0a, 0x24, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0xcb, 0x03, 0x0a, 0x0f, 0x45, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x11, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x42, 0x74, 0x63, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73,
	0x12, 0x22, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x42, 0x74, 0x63, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x42, 0x74, 0x63, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x74, 0x0a, 0x19, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x12, 0x2a, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x65, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x42, 0x74, 0x63, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x73, 0x12, 0x25, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x42, 0x74, 0x63, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x42, 0x74, 0x63, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7d, 0x0a, 0x1c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x61, 0x6c, 0x73, 0x12, 0x2d, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x72, 0x61, 0x2d, 0x6e, 0x77, 0x2f, 0x62, 0x74, 0x63, 0x2d,
	0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_envelope_proto_rawDescOnce sync.Once
	file_protos_envelope_proto_rawDescData = file_protos_envelope_proto_rawDesc
)

func file_protos_envelope_proto_rawDescGZIP() []byte {
	file_protos_envelope_proto_rawDescOnce.Do(func() {
		file_protos_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_envelope_proto_rawDescData)
	})
	return file_protos_envelope_proto_rawDescData
}

var file_protos_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_envelope_proto_goTypes = []interface{}{
	(*VerifyBtcDepositsRequest)(nil),             // 0: envelope.VerifyBtcDepositsRequest
	(*BtcDepositTx)(nil),                         // 1: envelope.BtcDepositTx
	(*VerifyBtcDepositsResponse)(nil),            // 2: envelope.VerifyBtcDepositsResponse
	(*VerifyInscriptionDepositsRequest)(nil),     // 3: envelope.VerifyInscriptionDepositsRequest
	(*InscriptionDepositTx)(nil),                 // 4: envelope.InscriptionDepositTx
	(*VerifyInscriptionDepositsResponse)(nil),    // 5: envelope.VerifyInscriptionDepositsResponse
	(*VerifyBtcWithdrawalsRequest)(nil),          // 6: envelope.VerifyBtcWithdrawalsRequest
	(*VerifyBtcWithdrawalsResponse)(nil),         // 7: envelope.VerifyBtcWithdrawalsResponse
	(*VerifyInscriptionWithdrawalsRequest)(nil),  // 8: envelope.VerifyInscriptionWithdrawalsRequest
	(*VerifyInscriptionWithdrawalsResponse)(nil), // 9: envelope.VerifyInscriptionWithdrawalsResponse
}
var file_protos_envelope_proto_depIdxs = []int32{
	1, // 0: envelope.VerifyBtcDepositsRequest.txs:type_name -> envelope.BtcDepositTx
	0, // 1: envelope.EnvelopeService.VerifyBtcDeposits:input_type -> envelope.VerifyBtcDepositsRequest
	3, // 2: envelope.EnvelopeService.VerifyInscriptionDeposits:input_type -> envelope.VerifyInscriptionDepositsRequest
	6, // 3: envelope.EnvelopeService.VerifyBtcWithdrawals:input_type -> envelope.VerifyBtcWithdrawalsRequest
	8, // 4: envelope.EnvelopeService.VerifyInscriptionWithdrawals:input_type -> envelope.VerifyInscriptionWithdrawalsRequest
	2, // 5: envelope.EnvelopeService.VerifyBtcDeposits:output_type -> envelope.VerifyBtcDepositsResponse
	5, // 6: envelope.EnvelopeService.VerifyInscriptionDeposits:output_type -> envelope.VerifyInscriptionDepositsResponse
	7, // 7: envelope.EnvelopeService.VerifyBtcWithdrawals:output_type -> envelope.VerifyBtcWithdrawalsResponse
	9, // 8: envelope.EnvelopeService.VerifyInscriptionWithdrawals:output_type -> envelope.VerifyInscriptionWithdrawalsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_envelope_proto_init() }
func file_protos_envelope_proto_init() {
	if File_protos_envelope_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_envelope_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyBtcDepositsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_envelope_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcDepositTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_envelope_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyBtcDepositsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_envelope_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyInscriptionDepositsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_envelope_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InscriptionDepositTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_envelope_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyInscriptionDepositsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_envelope_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyBtcWithdrawalsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_envelope_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyBtcWithdrawalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_envelope_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyInscriptionWithdrawalsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_envelope_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyInscriptionWithdrawalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_envelope_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_envelope_proto_goTypes,
		DependencyIndexes: file_protos_envelope_proto_depIdxs,
		MessageInfos:      file_protos_envelope_proto_msgTypes,
	}.Build()
	File_protos_envelope_proto = out.File
	file_protos_envelope_proto_rawDesc = nil
	file_protos_envelope_proto_goTypes = nil
	file_protos_envelope_proto_depIdxs = nil
}
